insert into public.prompt_cards (id, prompt_text, category, content_rating, is_active)
overriding system value
values
(1, 'At the family reunion, nobody expected __________.', 'base', 'adult', true),
(2, 'My browser history would be less embarrassing if it didn’t include __________.', 'base', 'adult', true),
(3, 'The quickest way to ruin date night is __________.', 'base', 'adult', true),
(4, 'Nothing says “I’m an adult” like __________.', 'base', 'adult', true),
(5, 'The real reason the neighbors stopped waving is __________.', 'base', 'adult', true),
(6, 'My safe word is apparently __________.', 'base', 'adult', true),
(7, 'The worst thing to hear during a massage is __________.', 'base', 'adult', true),
(8, 'Tonight’s special is __________ served with a side of regret.', 'base', 'adult', true),
(9, 'The priest paused the ceremony because of __________.', 'base', 'adult', true),
(10, 'My retirement plan currently consists of __________.', 'base', 'adult', true),
(11, 'The one thing guaranteed to kill the mood is __________.', 'base', 'adult', true),
(12, 'I knew the vacation was over when I saw __________.', 'base', 'adult', true),
(13, 'The secret ingredient in Grandma’s recipe is __________.', 'base', 'adult', true),
(14, 'HR would like everyone to stop discussing __________.', 'base', 'adult', true),
(15, 'The group chat was permanently deleted after __________.', 'base', 'adult', true),
(16, 'My greatest contribution to society is __________.', 'base', 'adult', true),
(17, 'The hotel charged us extra for __________.', 'base', 'adult', true),
(18, 'I accidentally became locally famous for __________.', 'base', 'adult', true),
(19, 'The phrase “technically legal” usually comes before __________.', 'base', 'adult', true),
(20, 'Nothing brings a family together like __________.', 'base', 'adult', true),
(21, 'The worst possible tattoo would be __________.', 'base', 'adult', true),
(22, 'At 2:00 a.m., I made the regrettable decision to __________.', 'base', 'adult', true),
(23, 'My doctor says I need to cut back on __________.', 'base', 'adult', true),
(24, 'The HOA has issued a formal warning about __________.', 'base', 'adult', true),
(25, 'My love language is __________.', 'base', 'adult', true),
(26, 'The bachelor party ended immediately after __________.', 'base', 'adult', true),
(27, 'The weirdest thing to find under the bed is __________.', 'base', 'adult', true),
(28, 'I lost the argument when they brought up __________.', 'base', 'adult', true),
(29, 'The school fundraiser took a dark turn when someone donated __________.', 'base', 'adult', true),
(30, 'My search for inner peace ended with __________.', 'base', 'adult', true),
(31, 'The only thing keeping this marriage together is __________.', 'base', 'adult', true),
(32, 'I would sell my soul for __________.', 'base', 'adult', true),
(33, 'The new company mascot is __________.', 'base', 'adult', true),
(34, 'Nobody warned me that adulthood involved so much __________.', 'base', 'adult', true),
(35, 'The first red flag was __________.', 'base', 'adult', true),
(36, 'My emergency contact refuses to discuss __________.', 'base', 'adult', true),
(37, 'The worst possible thing to yell in church is __________.', 'base', 'adult', true),
(38, 'The neighborhood barbecue is now remembered for __________.', 'base', 'adult', true),
(39, 'My therapist says I use humor to avoid talking about __________.', 'base', 'adult', true),
(40, 'The phrase “hold my beer” was followed by __________.', 'base', 'adult', true),
(41, 'The job interview went well until I mentioned __________.', 'base', 'adult', true),
(42, 'My personal brand can best be described as __________.', 'base', 'adult', true),
(43, 'The police report simply listed the cause as __________.', 'base', 'adult', true),
(44, 'At this age, romance mostly means __________.', 'base', 'adult', true),
(45, 'The most inappropriate wedding gift is __________.', 'base', 'adult', true),
(46, 'My side hustle is secretly __________.', 'base', 'adult', true),
(47, 'The reason I can never return to Costco is __________.', 'base', 'adult', true),
(48, 'The worst thing to discover in a hot tub is __________.', 'base', 'adult', true),
(49, 'I knew the edible had kicked in when __________.', 'base', 'adult', true),
(50, 'The family Christmas card accidentally featured __________.', 'base', 'adult', true),
(51, 'The new flavor of energy drink is __________.', 'base', 'adult', true),
(52, 'The apocalypse will probably begin with __________.', 'base', 'adult', true),
(53, 'My biggest irrational fear is __________.', 'base', 'adult', true),
(54, 'The best part of working from home is __________.', 'base', 'adult', true),
(55, 'The worst excuse for being late is __________.', 'base', 'adult', true),
(56, 'The surprise inside the piñata was __________.', 'base', 'adult', true),
(57, 'I got kicked out of trivia night for answering __________.', 'base', 'adult', true),
(58, 'The restaurant’s new slogan is “Come for the food, stay for __________.”', 'base', 'adult', true),
(59, 'The true meaning of friendship is __________.', 'base', 'adult', true),
(60, 'The only acceptable reason to fake your own death is __________.', 'base', 'adult', true),
(61, 'The worst thing to bring on a first date is __________.', 'base', 'adult', true),
(62, 'The neighborhood watch is currently investigating __________.', 'base', 'adult', true),
(63, 'My final words will probably be __________.', 'base', 'adult', true),
(64, 'The reunion got awkward when someone mentioned __________.', 'base', 'adult', true),
(65, 'My most questionable Amazon purchase was __________.', 'base', 'adult', true),
(66, 'The government is covering up __________.', 'base', 'adult', true),
(67, 'The worst thing to whisper during a funeral is __________.', 'base', 'adult', true),
(68, 'My new fitness routine involves __________.', 'base', 'adult', true),
(69, 'The headline tomorrow will read: “Local Parent Arrested for __________.”', 'base', 'adult', true),
(70, 'The cruise ship buffet was shut down because of __________.', 'base', 'adult', true),
(71, 'The family dog has developed an unhealthy obsession with __________.', 'base', 'adult', true),
(72, 'I regret teaching my child about __________.', 'base', 'adult', true),
(73, 'The worst item to find in a church donation bin is __________.', 'base', 'adult', true),
(74, 'The fastest way to get uninvited from game night is __________.', 'base', 'adult', true),
(75, 'My dream home absolutely must include __________.', 'base', 'adult', true),
(76, 'The real reason dinosaurs went extinct was __________.', 'base', 'adult', true),
(77, 'The hardest part about being sexy is __________.', 'base', 'adult', true),
(78, 'Things got weird at karaoke when Dad performed __________.', 'base', 'adult', true),
(79, 'My boss described my performance as “an impressive display of __________.”', 'base', 'adult', true),
(80, 'The new dating app matches people based on __________.', 'base', 'adult', true),
(81, 'The first thing I’d buy after winning the lottery is __________.', 'base', 'adult', true),
(82, 'The weird smell in the basement turned out to be __________.', 'base', 'adult', true),
(83, 'The key to a lasting relationship is pretending to enjoy __________.', 'base', 'adult', true),
(84, 'The worst possible nickname is __________.', 'base', 'adult', true),
(85, 'My autobiography will be titled __________.', 'base', 'adult', true),
(86, 'The real purpose of the office supply closet is __________.', 'base', 'adult', true),
(87, 'The worst thing to hear from your Uber driver is __________.', 'base', 'adult', true),
(88, 'The family vacation slideshow contained way too much __________.', 'base', 'adult', true),
(89, 'My biggest accomplishment this year is avoiding __________.', 'base', 'adult', true),
(90, 'The secret to surviving Thanksgiving is __________.', 'base', 'adult', true),
(91, 'The worst possible item to bring through airport security is __________.', 'base', 'adult', true),
(92, 'My neighbors think I’m running an illegal business involving __________.', 'base', 'adult', true),
(93, 'The new holiday tradition is __________.', 'base', 'adult', true),
(94, 'The only thing worse than taxes is __________.', 'base', 'adult', true),
(95, 'The company picnic was canceled due to __________.', 'base', 'adult', true),
(96, 'My hidden talent is __________.', 'base', 'adult', true),
(97, 'The most disappointing superpower would be __________.', 'base', 'adult', true),
(98, 'The official cause of the divorce was __________.', 'base', 'adult', true),
(99, 'The menu described it as “artisan,” but it was clearly __________.', 'base', 'adult', true),
(100, 'The worst thing to say after “I love you” is __________.', 'base', 'adult', true),
(101, 'My new podcast is entirely about __________.', 'base', 'adult', true),
(102, 'The reason the Wi-Fi is so slow is __________.', 'base', 'adult', true),
(103, 'The weirdest thing to inherit from a relative is __________.', 'base', 'adult', true),
(104, 'The hotel continental breakfast now includes __________.', 'base', 'adult', true),
(105, 'My future self came back to warn me about __________.', 'base', 'adult', true),
(106, 'The best way to get through jury duty is __________.', 'base', 'adult', true),
(107, 'The worst possible thing to put in a time capsule is __________.', 'base', 'adult', true),
(108, 'I was banned from the petting zoo for __________.', 'base', 'adult', true),
(109, 'The sign on the door says “Absolutely no __________.”', 'base', 'adult', true),
(110, 'The neighborhood Facebook group is furious about __________.', 'base', 'adult', true),
(111, 'My most toxic trait is __________.', 'base', 'adult', true),
(112, 'The strangest item on the wedding registry was __________.', 'base', 'adult', true),
(113, 'The new wellness trend involves __________.', 'base', 'adult', true),
(114, 'My financial advisor strongly discourages __________.', 'base', 'adult', true),
(115, 'The worst thing to discover during home renovations is __________.', 'base', 'adult', true),
(116, 'The best thing about being single is __________.', 'base', 'adult', true),
(117, 'The PTA meeting ended after a heated debate about __________.', 'base', 'adult', true),
(118, 'The real reason the meeting could not have been an email was __________.', 'base', 'adult', true),
(119, 'The most cursed flavor of ice cream is __________.', 'base', 'adult', true),
(120, 'My emergency preparedness kit contains __________.', 'base', 'adult', true),
(121, 'The only thing I remember from college is __________.', 'base', 'adult', true),
(122, 'The weirdest thing to say while meeting the in-laws is __________.', 'base', 'adult', true),
(123, 'The theme of this year’s office party is __________.', 'base', 'adult', true),
(124, 'The worst thing to find in your spouse’s nightstand is __________.', 'base', 'adult', true),
(125, 'My greatest fear about artificial intelligence is __________.', 'base', 'adult', true),
(126, 'The family talent show was won by __________.', 'base', 'adult', true),
(127, 'The worst possible thing to engrave on a tombstone is __________.', 'base', 'adult', true),
(128, 'The neighborhood kids now refer to me as __________.', 'base', 'adult', true),
(129, 'The restaurant was awarded one star for __________.', 'base', 'adult', true),
(130, 'The first sign that the camping trip was doomed was __________.', 'base', 'adult', true),
(131, 'My doctor looked concerned when I mentioned __________.', 'base', 'adult', true),
(132, 'The best way to spice up a boring meeting is __________.', 'base', 'adult', true),
(133, 'The worst item to accidentally send in a work email is __________.', 'base', 'adult', true),
(134, 'The secret menu item is __________.', 'base', 'adult', true),
(135, 'My next bad decision will involve __________.', 'base', 'adult', true),
(136, 'The strangest reason to call 911 is __________.', 'base', 'adult', true),
(137, 'The family group photo was ruined by __________.', 'base', 'adult', true),
(138, 'The worst possible answer to “Where do you see yourself in five years?” is __________.', 'base', 'adult', true),
(139, 'The new fragrance from a luxury brand smells like __________.', 'base', 'adult', true),
(140, 'My biggest problem with organized religion is the lack of __________.', 'base', 'adult', true),
(141, 'The most suspicious thing to keep in your trunk is __________.', 'base', 'adult', true),
(142, 'The city council has voted to ban __________.', 'base', 'adult', true),
(143, 'The worst possible prize in a cereal box is __________.', 'base', 'adult', true),
(144, 'My child’s school project was accidentally about __________.', 'base', 'adult', true),
(145, 'The best excuse for leaving a party early is __________.', 'base', 'adult', true),
(146, 'The weirdest thing to hear through the hotel wall is __________.', 'base', 'adult', true),
(147, 'The official drink of bad decisions is __________.', 'base', 'adult', true),
(148, 'The worst part about being attractive is constantly dealing with __________.', 'base', 'adult', true),
(149, 'My spouse says I spend too much money on __________.', 'base', 'adult', true),
(150, 'The real reason I joined the gym is __________.', 'base', 'adult', true),
(151, 'The most inappropriate thing to bring to a baby shower is __________.', 'base', 'adult', true),
(152, 'The reason this room smells strange is __________.', 'base', 'adult', true),
(153, 'My favorite way to avoid responsibility is __________.', 'base', 'adult', true),
(154, 'The family lawyer advised us never to speak of __________.', 'base', 'adult', true),
(155, 'The worst possible thing to hear from a pilot is __________.', 'base', 'adult', true),
(156, 'The new reality show traps eight strangers in a house with __________.', 'base', 'adult', true),
(157, 'The only thing standing between me and success is __________.', 'base', 'adult', true),
(158, 'The neighborhood yard sale featured an alarming amount of __________.', 'base', 'adult', true),
(159, 'My midlife crisis will probably involve __________.', 'base', 'adult', true),
(160, 'The best thing to yell before jumping into a pool is __________.', 'base', 'adult', true)
on conflict (id) do update
set
  prompt_text = excluded.prompt_text,
  category = excluded.category,
  content_rating = excluded.content_rating,
  is_active = excluded.is_active;
