create extension if not exists pgcrypto;

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  room_code varchar(4) unique not null,
  name text not null,
  host_user_id uuid not null,
  status text not null check (status in ('lobby', 'active', 'ended')),
  current_round_id uuid null,
  current_presenter_player_id uuid null,
  round_number integer not null default 0,
  created_at timestamptz not null default now(),
  started_at timestamptz null,
  ended_at timestamptz null,
  settings jsonb not null default '{}'::jsonb
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null,
  nickname varchar(32) not null,
  seat_order integer not null,
  score integer not null default 0,
  is_host boolean not null default false,
  is_active boolean not null default true,
  is_connected boolean not null default true,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(game_id, user_id),
  unique(game_id, seat_order)
);

create table if not exists public.prompt_cards (
  id bigint generated by default as identity primary key,
  prompt_text text not null,
  category text not null default 'base',
  content_rating text not null default 'adult',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.game_prompt_deck (
  game_id uuid not null references public.games(id) on delete cascade,
  prompt_card_id bigint not null references public.prompt_cards(id),
  deck_position integer not null,
  used_at timestamptz null,
  primary key (game_id, prompt_card_id),
  unique (game_id, deck_position)
);

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  round_number integer not null,
  presenter_player_id uuid not null references public.players(id),
  prompt_card_id bigint not null references public.prompt_cards(id),
  status text not null check (status in ('collecting', 'ready_for_judging', 'judging', 'winner_selected', 'completed', 'cancelled')),
  started_at timestamptz not null default now(),
  submission_deadline_warning_at timestamptz not null,
  all_submitted_at timestamptz null,
  winner_response_id uuid null,
  completed_at timestamptz null,
  unique(game_id, round_number)
);

create table if not exists public.responses (
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.rounds(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  response_text text not null,
  display_order integer null,
  submitted_at timestamptz not null default now(),
  is_winner boolean not null default false,
  unique(round_id, player_id)
);

alter table public.rounds
  add constraint rounds_winner_response_id_fkey
  foreign key (winner_response_id) references public.responses(id)
  on delete set null;

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  round_id uuid null references public.rounds(id) on delete cascade,
  event_type text not null,
  actor_player_id uuid null references public.players(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.games enable row level security;
alter table public.players enable row level security;
alter table public.prompt_cards enable row level security;
alter table public.game_prompt_deck enable row level security;
alter table public.rounds enable row level security;
alter table public.responses enable row level security;
alter table public.game_events enable row level security;

create or replace function public.is_game_member(target_game_id uuid)
returns boolean
language sql
stable
security invoker
as $$
  select exists (
    select 1
    from public.players
    where game_id = target_game_id
      and user_id = auth.uid()
      and is_active = true
  );
$$;

create policy "members can view their games"
on public.games
for select
to authenticated
using (public.is_game_member(id));

create policy "members can view players in their games"
on public.players
for select
to authenticated
using (public.is_game_member(game_id));

create policy "members can view rounds in their games"
on public.rounds
for select
to authenticated
using (public.is_game_member(game_id));

create policy "members can read prompt cards"
on public.prompt_cards
for select
to authenticated
using (true);

create policy "members can view prompt decks in their games"
on public.game_prompt_deck
for select
to authenticated
using (public.is_game_member(game_id));

create policy "players can view only their own responses"
on public.responses
for select
to authenticated
using (
  exists (
    select 1
    from public.players
    join public.rounds on public.rounds.id = public.responses.round_id
    where public.players.id = public.responses.player_id
      and public.players.user_id = auth.uid()
      and public.is_game_member(public.rounds.game_id)
  )
);

create policy "members can view game events"
on public.game_events
for select
to authenticated
using (public.is_game_member(game_id));
